### ISSUE TITLE
Failed test cases not showing properly

### ISSUE THREAD

**Issue by vkumarv** [getgauge-examples/gauge-example-groovy#4]
@Apoorva-GA
I have created spec file and implementation file, after that I have executed through maven, actually my test case is failed because of xpath issues but in gauge reports still it sowing as passed, please let me know the solution. Thanks for your support.

**Comment by Apoorva-GA** [comment]
@vkumarv Are you running it from console or any IDE?Is that step marked as failed there ? 
Also it will be useful if you could give an example project where we can reproduce this issue.

**Comment by vkumarv** [comment]
@Apoorva-GA ,
I am running from IntelliJ tool, I had given incorrect xpath to generate failed Gauge report for demo purpose. I have executed using spec file, Maven and Terminal but I am getting same issue. 

Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.8)
java (0.7.2)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

**Comment by negiDharmendra** [comment]
@vkumarv We are unable to replicate this issue. 

**My setup:**

gauge -v
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.8)
java (0.7.2)
screenshot (0.0.1)

IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
Licensed to ThoughtWorks, Inc / Dharmendra Negi
Subscription is active until November 2, 2019
JRE: 1.8.0_202-release-1483-b44 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

Gauge-IntelliJ plugin version: v0.3.15

----
**Steps I followed:**
- Cloned https://github.com/getgauge-examples/groovy-selenium.git
- Followed the instruction mentioned in [README.md](https://github.com/getgauge-examples/groovy-selenium/blob/master/README.md) to run the specs. 

First time worked fine. To replicate this issue, I have modified the `SignUpPage.user_username` to `SignUpPage.user_usernamefoo`. Ran all the specs from IntelliJ, everything worked as expected. I could see the failing scenarios marked as failed on the HTML report.

**Comment by negiDharmendra** [comment]
It will be a great help if you can share an example project to replicate this issue.

**Comment by zabil** [comment]
This happens when you catch errors in the `try` and `catch` block. for e.g

```
@step(...)
pubic void test() {
 try {
   // code with xpath error
 } catch () {}
}
```

If that is the case please remove the `try/catch` block to make the code look like

```
@step(...)
pubic void test() {
 // code with xpath error
}
```

But like @negiDharmendra and @Apoorva-GA  has asked before please share the step implementation or a sample project to replicate this issue.

**Comment by vkumarv** [comment]
@zabil @Apoorva-GA @negiDharmendra 

Thanks for quick response, I removed try catch in my code then report is generating properly(showing failed report also), could you please tell me why we need to remove try catch in my code, actually in my framework so many class files i have used try catch.

**Comment by zabil** [comment]
It is ok to have the the `try` `catch` block in your code. But you should not have a `try` `catch` block in your *test* code unless you are handling the error to not report a failure. 

Like junit and other testing frameworks Gauge marks a test failed only when an exception is thrown from the test method. In your case you are ignoring the exception.

You can read up more about this here https://stackoverflow.com/questions/31423643/try-catch-in-a-junit-test

**Comment by vkumarv** [comment]
@zabil, 
If I am not using try catch in my code, how can we generate user defined failed step report in index.html file.

Example: In below method, if element is not found then exception is showing in report but used defined step is not displayed in report like "Verify Text box" "Text box not found".

 public boolean type(By locator, String testdata, String locatorName) 
        {
                  driver.findElement(locator).clear();
                Thread.sleep(1000);
                driver.findElement(locator).sendKeys(testdata);
                flag = true;
                if (!flag) {
                    Gauge.writeMessage("Type "+"Data typing action is not perform on " + locatorName + " with data is " + testdata.replace(":", ""));
                     return true;
                } else if (b && flag) {
                    Gauge.writeMessage("Type "+"Data typing action is performed on " + locatorName + " with data is " + testdata.replace(":", ""));

                    /

                }

            }

Do we have any options like Gauge.writeMessage.Pass and Gauge.writeMessage.Fail in gauge? Please let me know.

**Comment by zabil** [comment]
As mentioned in earlier comments please throw an exception.
For example 
```
if (!flag) {
Gauge.writeMessage("Type "+"Data typing action is not perform on " + locatorName + " with data is " + testdata.replace(":", ""));
throw new RuntimeException("Action not performed")
}
```

**Comment by vkumarv** [comment]
Ok fine thanks.
